### PR TITLE
Upgrade p256 from v0.10 => v0.13.

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
This PR upgrades the version of `p256`, and addresses the breaking changes introduced by this upgrade. Upgrading this dependency allows `passkey-rs` to transitively install newer versions of the `signature` crate. The version of `signature` required by p256@v0.10 is incompatible with other cryptography crates in the ecosystem.

Closes https://github.com/1Password/passkey-rs/issues/3

FWIW, I'm happy to address any style changes you might prefer. I didn't put much thought into variable naming; I just made the minimum changes. Happy to improve the code quality at the request of reviewers. ^.^

### CODE REVIEW

**Review by hariria — APPROVED** [review]
Not sure if this will help but lgtm!

**Comment by hariria** [comment]
Could the signature crate also be updated per-chance?

**Review by Progdrasil — APPROVED** [review]

**Comment by Progdrasil** [comment]
I'm at the point of being able to merge this PR. Thank you for the contribution and your patience!

**Comment by RobbieMcKinstry** [comment]
No problem! Thanks for merging, and for updating the `signature` crate.

**Pull request merged**
